### 회원가입 ( 고객 )
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "2023-08-11",
  "email": "hyomyang@gmail.com",
  "name": "string",
  "password": "string",
  "phone": "string"
}

### 이메일 인증 ( 고객 )
GET http://localhost:8081/signup/customer/verify?email=hyomyang@gmail.com&code=hHhwz27uXj

### 로그인 ( 고객 )
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "hyomyang@gmail.com",
  "password": "string"
}

### 회원 정보 조회 ( 고객 )

GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2dTRDeHFmdTE2SWVPNndyNzVEQjNBQlFTSHFOaTdqY1FGa0dUS3BnUGRvPSIsImp0aSI6IlNZZVZDd2I0RHNGZEtZNnd4UndsSkE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2OTE5NTE4ODAsImV4cCI6MTY5MjAzODI4MH0.LDbeiTQsBXcXjBtjew2b2CcTMXp27Cw_6GSBBBdZs8g


### 잔액 변경 ( 고객 )
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2dTRDeHFmdTE2SWVPNndyNzVEQjNBQlFTSHFOaTdqY1FGa0dUS3BnUGRvPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2OTI0NzI0NTMsImV4cCI6MTY5MjU1ODg1M30.gJi2z003qnQylQmfBpHQObkqVnKw0s9lfKbWrJK09sk

{
  "from": "pagooo",
  "message": "HI",
  "money": 200000
}


#########################

### 회원가입 ( 셀러 )
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "2023-08-11",
  "email": "pagooo@naver.com",
  "name": "string",
  "password": "string",
  "phone": "string"
}

### 이메일 인증 ( 셀러 )
GET http://localhost:8081/signup/seller/verify?email=pagooo@naver.com&code=LWbHCJmvcJ

### 로그인 ( 셀러 )
POST http://localhost:8081/signin/seller
Content-Type: application/json

{
  "email": "pagooo@naver.com",
  "password": "string"
}