### 상품추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMzY3MTk4LCJleHAiOjE2OTI0NTM1OTh9.7IdIjuRtnmdrvN5oeTiL_iMHmfMOoH80MxrrWZIH03s

{
  "description": "상품 설명",
  "items": [
  ],
  "name": "아이패드"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMzY3MTk4LCJleHAiOjE2OTI0NTM1OTh9.7IdIjuRtnmdrvN5oeTiL_iMHmfMOoH80MxrrWZIH03s

    {
      "productId": 1,
      "count": 10,
      "name": "애플팬슬",
      "price": 10000
    }


### 상품수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMTIyNTY0LCJleHAiOjE2OTIyMDg5NjR9.8JigbHlSWOzdBzLZ7EecZzNYF9sFJaG4X6IgtAWPTJo

{
  "description": "맥북좋아",
  "items": [

  ],
  "id": 1,
  "name": "맥북프로2"
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMzY3MTk4LCJleHAiOjE2OTI0NTM1OTh9.7IdIjuRtnmdrvN5oeTiL_iMHmfMOoH80MxrrWZIH03s

{
  "id":1,
  "productId": 1,
  "count": 2,
  "name": "애플팬슬",
  "price": 10
}


### 상품삭제
DELETE http://localhost:8082/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMzY3MTk4LCJleHAiOjE2OTI0NTM1OTh9.7IdIjuRtnmdrvN5oeTiL_iMHmfMOoH80MxrrWZIH03s



### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=3
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMzY3MTk4LCJleHAiOjE2OTI0NTM1OTh9.7IdIjuRtnmdrvN5oeTiL_iMHmfMOoH80MxrrWZIH03s



### 상품검색
GET http://localhost:8082/search/product?name=아이패드
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMzY3MTk4LCJleHAiOjE2OTI0NTM1OTh9.7IdIjuRtnmdrvN5oeTiL_iMHmfMOoH80MxrrWZIH03s



### 상품 아이템 검색
GET http://localhost:8082/search/product/detail?productId=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMzY3MTk4LCJleHAiOjE2OTI0NTM1OTh9.7IdIjuRtnmdrvN5oeTiL_iMHmfMOoH80MxrrWZIH03s


### 카트 추가
POST http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMzY3MTk4LCJleHAiOjE2OTI0NTM1OTh9.7IdIjuRtnmdrvN5oeTiL_iMHmfMOoH80MxrrWZIH03s

{
  "description": "상품 설명",
  "id": 1,
  "items": [
    {
      "count": 2,
      "id": 1,
      "name": "애플팬슬",
      "price": 100
    }
  ],
  "name": "아이패드",
  "sellerId": 1
}

### 카트 보기
GET http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMzY3MTk4LCJleHAiOjE2OTI0NTM1OTh9.7IdIjuRtnmdrvN5oeTiL_iMHmfMOoH80MxrrWZIH03s
