### 상품추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMDk1NDI1LCJleHAiOjE2OTIxODE4MjV9.5KdlnIMNXvR_7aN2dnKLfJ1u3uWI4roGiHt3cMevke4

{
  "description": "상품 설명",
  "items": [
  ],
  "name": "아이패드"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMWS9FU0w4SndEQS8vcVdxdmdVR3lIdk54NHA0UzVTZFlxeXdBZWJjSFVJPSIsImp0aSI6ImRraExVenBYMmJ2d1NQdHZYNkNnS0E9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkyMDk1NDI1LCJleHAiOjE2OTIxODE4MjV9.5KdlnIMNXvR_7aN2dnKLfJ1u3uWI4roGiHt3cMevke4

    {
      "productId": 1,
      "count": 2,
      "name": "애플팬슬",
      "price": 100000
    }
